#!/usr/bin/env python3
"""Generates docs/api.md: a single-page API reference, one section per
`lib/*.sv0` module, one entry per public function — signature, contract
clauses (`requires`/`ensures`), and its DOC-001 doc comment.

Reuses check_doc_comments.py's own function-discovery and doc-comment
lookup (same file, same import, so the two scripts can never disagree
about what counts as a public function or a qualifying doc comment).

Regenerated on every `scripts/ci` run, like docs/requirement_test_matrix.md
-- do not hand-edit docs/api.md.

Usage: python3 scripts/gen_api_docs.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
LIB = HERE / "lib"
OUT = HERE / "docs" / "api.md"

sys.path.insert(0, str(Path(__file__).resolve().parent))
import check_doc_comments as cdc  # noqa: E402

HEADER_COMMENT_RE = re.compile(r"\A/\*(.*?)\*/", re.DOTALL)
MODULE_PREFIX_RE = re.compile(r"^module::\S+\s*—\s*")
SIG_END_RE = re.compile(r"\s*\{\s*$")
CONTRACT_RE = re.compile(r"^\s*(requires|ensures)\(")


def module_summary(text: str) -> str:
    """The first sentence of the file's own leading header comment (its
    module-level doc comment), stripped of the `module::NAME — ` prefix
    convention where present (arith/complex/modular/polar/trig; prelude.sv0
    has no such prefix)."""
    m = HEADER_COMMENT_RE.match(text.lstrip())
    if not m:
        return ""
    body = m.group(1)
    lines = [ln.strip().lstrip("*").strip() for ln in body.splitlines()]
    joined = re.sub(r"\s+", " ", " ".join(lines)).strip()
    joined = MODULE_PREFIX_RE.sub("", joined)
    sentence_end = joined.find(". ")
    if sentence_end == -1:
        sentence_end = len(joined) - 1 if joined.endswith(".") else len(joined)
    return joined[: sentence_end + 1].strip()


def signature_and_contracts(lines: list[str], fn_lineno: int) -> tuple[str, list[str]]:
    """fn_lineno is 1-based. Returns (signature line without trailing '{',
    [contract clause strings])."""
    sig = lines[fn_lineno - 1]
    sig = SIG_END_RE.sub("", sig).rstrip()
    contracts = []
    i = fn_lineno
    while i < len(lines) and CONTRACT_RE.match(lines[i]):
        contracts.append(lines[i].strip().rstrip("{").rstrip())
        i += 1
    return sig, contracts


def doc_prose(doc: str | None) -> str:
    """Strip /* */ and leading ' * ' per-line markers, return prose."""
    if doc is None:
        return "_undocumented (internal helper)_"
    body = doc.strip()
    if body.startswith("/*"):
        body = body[2:]
    if body.endswith("*/"):
        body = body[:-2]
    out_lines = []
    for line in body.splitlines():
        line = line.strip()
        if line.startswith("*"):
            line = line[1:].strip()
        out_lines.append(line)
    return "\n".join(out_lines).strip()


def main() -> int:
    sections = []
    total = 0

    for path in sorted(LIB.glob("*.sv0")):
        text = path.read_text(encoding="utf-8")
        lines = text.splitlines()
        modname = path.stem
        summary = module_summary(text)

        entries = []
        for name, lineno in cdc.find_functions(path):
            if name in cdc.INTERNAL_HELPERS:
                continue
            total += 1
            sig, contracts = signature_and_contracts(lines, lineno)
            doc = cdc.doc_comment_above(lines, lineno - 1)
            entries.append((name, sig, contracts, doc_prose(doc)))

        if not entries:
            continue

        header = f"## `{modname}`\n\n{summary}\n" if summary else f"## `{modname}`\n"
        parts = [header]
        for name, sig, contracts, prose in sorted(entries, key=lambda e: e[0]):
            parts.append(f"### `{name}`\n")
            code_block = "```sv0\n" + sig
            if contracts:
                code_block += "\n    " + "\n    ".join(contracts)
            code_block += "\n```\n"
            parts.append(code_block)
            parts.append(prose + "\n")
        sections.append("\n".join(parts))

    out_lines = [
        "# API reference",
        "",
        "Generated by `scripts/gen_api_docs.py` from each `lib/*.sv0` module's",
        "own doc comments (DOC-001) — do not hand-edit. One section per module,",
        "one entry per public function, in the order `use <module>::<fn>;`",
        "would name it. Non-exact (ULP-budgeted) functions link their own doc",
        "comment's `docs/accuracy.md` cross-reference inline; see that file for",
        "the measured error tables themselves.",
        "",
        f"**{total} public functions across {len(sections)} modules.**",
        "",
        "---",
        "",
    ]
    out_lines.append("\n---\n\n".join(sections))

    OUT.write_text("\n".join(out_lines).rstrip() + "\n", encoding="utf-8")
    print(f"gen_api_docs: wrote {OUT.relative_to(HERE)} ({total} functions, {len(sections)} modules)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
