#!/usr/bin/env python3
"""COMPAT-002 / TEST-005 (per-fixture surface): drive every row of
`test/fixtures/rounding.csv` and `test/fixtures/trig.csv` through a live
`sv0`-compiled build on BOTH backends and check each result against the
fixture's own EXPECTED column.

Until now the fixture tables were verified against a live build exactly
once, by hand, when they were written (see `test/fixtures/manifest.md`'s
closing paragraph). `scripts/vm_behavioral_parity.py` (run from
`scripts/ci`) already proves the two backends AGREE on every self-test's
exit code, but nothing re-checked the fixture rows themselves, and
nothing ran them through `sv0vm` at all.

This script closes both gaps:

  1. It GENERATES a single `fn main() -> i32` sv0 program from the two
     CSVs — one check per (row, function), returning the 1-based ordinal
     of the first failing check (0 = every row matched its expected
     value).
  2. It compiles + runs that program on the C backend
     (`build/sv0-megatu-compiler-native --project` -> cc -> execute) and
     asserts exit 0 — the reproducible replacement for the old one-time
     manual check.
  3. It compiles + runs the SAME program on the VM backend
     (`build/sv0-megatu-vm-native --project` -> `.sv0b` -> `sv0vm`) and
     asserts the VM exit code equals the C exit code (and is 0) — the
     per-fixture cross-backend surface that `vm_behavioral_parity.py`'s
     exit-code-only comparison never reached.

On a mismatch it decodes the failing ordinal back to the CSV row and
function it came from, on whichever backend disagreed.

`PANIC` rows in `trig.csv` (documented `requires`-violation cases) can't
be exercised inside one non-crashing binary and are listed as skipped.

The **C backend leg gates** (a mismatch fails). The **VM backend leg is
advisory by default**: every check passes on SML/NJ 2026.1, but under the
SML/NJ 110.99.9 the CI runner uses, a transcendental `ensures` aborts the
run (a `sv0 contract violation` on the VM, not a value mismatch) — see
`BUGS.md`. The exit-code cross-backend gate (`vm_behavioral_parity.py`)
already proves both backends agree on every self-test the library ships;
this per-fixture VM leg becomes gating once that discrepancy is
root-caused. Pass `--strict-vm` to make the VM leg fail too.

Usage:
  python3 scripts/run_fixture_parity.py [--toolchain-root DIR] [--emit-only PATH]
                                        [--c-only] [--vm-only] [--strict-vm]
"""

from __future__ import annotations

import argparse
import csv
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
FIXTURES = HERE / "test" / "fixtures"
LIB = HERE / "lib"

ROUNDING_FUNCS = ("floor_f64", "ceil_f64", "round_f64", "trunc_f64")


# ── literal / expected token -> sv0 source expression ────────────────

def num_to_sv0(tok: str) -> str:
    """A CSV numeric cell -> an sv0 f64 expression. Handles the special
    tokens (`nan`/`inf`/`-inf`/`-0.0`), a plain negative (sv0's lexer
    has no negative float literal — the codebase writes `0.0 - v`), and
    an ordinary positive decimal (emitted verbatim, exact)."""
    t = tok.strip().lower()
    if t == "nan":
        return "(0.0 / 0.0)"
    if t in ("inf", "+inf"):
        return "(1.0 / 0.0)"
    if t == "-inf":
        return "(0.0 - (1.0 / 0.0))"
    if t == "-0.0":
        # true IEEE-754 negative zero: -1.0 * 0.0 (NOT 0.0 - 0.0, which is +0.0)
        return "((0.0 - 1.0) * 0.0)"
    if t.startswith("-"):
        return f"(0.0 - {t[1:]})"
    return t


def check_expr(got: str, want_tok: str, tol_tok: str) -> str:
    """An sv0 bool expression that is true iff `got` matches the fixture's
    expected cell `want_tok` under tolerance `tol_tok`."""
    w = want_tok.strip().lower()
    tol = tol_tok.strip().lower()
    if w == "nan":
        return f"fx_is_nan({got})"
    if w == "inf":
        return f"(fx_is_inf({got}) && ({got}) > 0.0)"
    if w == "-inf":
        return f"(fx_is_inf({got}) && ({got}) < 0.0)"
    want = num_to_sv0(want_tok)
    if tol and tol not in ("0.0", "0", "exact"):
        return f"(fx_abs({got} - {want}) <= {tol})"
    return f"fx_eq_exact({got}, {want})"


# ── program generation ──────────────────────────────────────────────

PRELUDE = """\
/* GENERATED by scripts/run_fixture_parity.py from the two fixture CSVs.
 * Do not edit or commit -- this file is staged into a throwaway --project
 * dir, compiled on both backends, and its exit code decoded back to the
 * failing fixture row. 0 = every row matched its expected value.
 * (Kept ASCII and free of a literal slash-star: sv0 nests block comments,
 * so an inner comment opener here would swallow the rest of the file.) */
use arith::floor_f64;
use arith::ceil_f64;
use arith::round_f64;
use arith::trunc_f64;
use arith::is_nan_f64;
use arith::is_infinite_f64;
use trig::sqrt_f64;
use trig::sin_f64;
use trig::cos_f64;
use trig::tan_f64;
use trig::asin_f64;
use trig::acos_f64;
use trig::atan_f64;
use trig::atan2_f64;
use trig::exp_f64;
use trig::ln_f64;

/* absolute value, kept local so the generator needs no dependency on
 * whichever module abs_f64 lives in. */
fn fx_abs(x: f64) -> f64 {
    if x < 0.0 { return 0.0 - x; }
    return x;
}

fn fx_is_nan(x: f64) -> bool {
    return is_nan_f64(x);
}

fn fx_is_inf(x: f64) -> bool {
    return is_infinite_f64(x);
}

/* exact match for the tolerance-0 fixture rows: NaN matches NaN,
 * everything else is IEEE-754 `==`. The sign of a zero result is NOT
 * distinguished — `ceil_f64`/`trunc_f64` of a small negative input
 * return +0.0 here where C's libm returns -0.0, and SPEC.md pins no
 * sign-of-zero for those; see test/fixtures/manifest.md. What this
 * runner does gate is that BOTH backends agree and both match the
 * fixture's value. */
fn fx_eq_exact(got: f64, want: f64) -> bool {
    if got != got { return want != want; }
    if want != want { return false; }
    return got == want;
}

fn main() -> i32 {
"""


def generate(rounding_rows, trig_rows):
    """Return (sv0_source, checks) where checks[i] describes the (i+1)-th
    emitted check (its 1-based ordinal is the exit code on failure)."""
    lines = [PRELUDE]
    checks: list[str] = []
    skipped: list[str] = []

    for r in rounding_rows:
        inp = num_to_sv0(r["input"])
        for fn in ROUNDING_FUNCS:
            want = r[f"{fn.split('_')[0]}_expected"]  # floor_f64 -> floor_expected
            expr = check_expr(f"{fn}({inp})", want, "0.0")
            ordv = len(checks) + 1
            lines.append(f"    if !({expr}) {{ return {ordv}; }}")
            checks.append(f"rounding.csv  input={r['input']!r:22}  {fn}  want={want!r}")

    for r in trig_rows:
        fn = r["function"].strip()
        want = r["expected"].strip()
        tol = (r.get("tolerance") or "").strip()
        i1 = r["input1"].strip()
        i2 = (r.get("input2") or "").strip()
        if want.upper() == "PANIC":
            skipped.append(f"trig.csv  {fn}({i1}{', ' + i2 if i2 else ''})  -> PANIC (requires-violation row)")
            continue
        args = num_to_sv0(i1)
        if i2:
            args += f", {num_to_sv0(i2)}"
        expr = check_expr(f"{fn}({args})", want, tol)
        ordv = len(checks) + 1
        lines.append(f"    if !({expr}) {{ return {ordv}; }}")
        checks.append(f"trig.csv      {fn}({i1}{', ' + i2 if i2 else ''})  want={want!r} tol={tol!r}")

    lines.append("    return 0;")
    lines.append("}")
    src = "\n".join(lines) + "\n"
    # sv0 nests block comments: a stray "/*" (e.g. from a "foo/*.csv" path
    # in a comment) opens an inner comment that never closes and silently
    # swallows the rest of the file. The three PRELUDE comment blocks are
    # the only legitimate openers; nothing generated from the CSV rows
    # should contain one.
    if src.count("/*") != 3 or src.count("/*") != src.count("*/"):
        raise SystemExit("run_fixture_parity: generated program has an "
                         "unexpected block-comment opener/closer count "
                         f"(/* = {src.count('/*')}, */ = {src.count('*/')})")
    return src, checks, skipped


# ── backend runners ────────────────────────────────────────────────

def stage_project(src: str, tmp: Path) -> Path:
    (tmp / "lib").symlink_to(LIB)
    # The check program sits at the project ROOT (not a subdir): the VM
    # emitter's --project main-detection only picks up a root-level entry
    # point, the same shape as sv0-mathlib's own main.sv0. The "zzz_"
    # prefix keeps it sorting AFTER "lib/" — BUGS.md #17: a top-level
    # entry sorting before "lib" breaks --project discovery silently.
    (tmp / "zzz_fixture_check.sv0").write_text(src, encoding="utf-8")
    return tmp


def run_c(project: Path, toolchain_root: Path) -> tuple[int | str, str]:
    compiler = toolchain_root / "build" / "sv0-megatu-compiler-native"
    runtime = toolchain_root / "sv0c" / "runtime"
    if not compiler.is_file():
        return "NO_COMPILER", str(compiler)
    c_path = project / "out.c"
    proc = subprocess.run([str(compiler), "--project", str(project)],
                          stdout=c_path.open("wb"), stderr=subprocess.PIPE)
    if proc.returncode != 0 or c_path.stat().st_size == 0:
        return "EMIT_FAIL", proc.stderr.decode(errors="replace")[-400:]
    binary = project / "fixture_bin"
    cc = subprocess.run(["cc", "-std=c99", "-O0", "-w", "-I", str(runtime),
                         str(c_path), str(runtime / "sv0_runtime.c"), "-o", str(binary)],
                        capture_output=True)
    if cc.returncode != 0:
        return "CC_FAIL", cc.stderr.decode(errors="replace")[-400:]
    run = subprocess.run([str(binary)], capture_output=True)
    return run.returncode, run.stdout.decode(errors="replace")


def run_vm(project: Path, toolchain_root: Path) -> tuple[int | str, str]:
    emitter = toolchain_root / "build" / "sv0-megatu-vm-native"
    sv0vm = toolchain_root / "sv0vm"
    if not emitter.is_file():
        return "NO_EMITTER", str(emitter)
    b_path = project / "out.sv0b"
    proc = subprocess.run([str(emitter)],
                          stdout=b_path.open("wb"), stderr=subprocess.PIPE,
                          env={**os.environ, "SV0_DRV_REQUEST": f"--project {project}"})
    if proc.returncode != 0 or b_path.stat().st_size == 0:
        return "EMIT_FAIL", proc.stderr.decode(errors="replace")[-400:]
    run = subprocess.run(["sml"], stdin=(sv0vm / "scripts" / "run_sv0b.sml").open(),
                         capture_output=True, text=True, cwd=sv0vm,
                         env={**os.environ, "SV0B": str(b_path)})
    out = run.stdout + run.stderr
    # The interpreter aborts a failed requires/ensures with exit code 1 AND
    # this stderr line -- surface it so a contract violation isn't decoded
    # as "check #1" (which is also exit 1).
    cv = re.search(r"sv0 contract violation: (.+)", out)
    m = re.search(r"vm_exit:(-?\d+)", out)
    if cv:
        return "CONTRACT_VIOLATION", cv.group(1).strip()
    if not m:
        return "NO_EXIT", out[-400:]
    return int(m.group(1)) & 0xFF, ""


# ── main ───────────────────────────────────────────────────────────

def decode(ordv, checks: list[str]) -> str:
    if not isinstance(ordv, int):
        return f"{ordv} (backend fault, not a fixture miss)"
    if 1 <= ordv <= len(checks):
        return f"check #{ordv}: {checks[ordv - 1]}"
    return f"exit {ordv} (out of range 1..{len(checks)} — a compile/runtime fault, not a fixture miss)"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--toolchain-root", type=Path,
                    default=Path(os.environ.get("SV0_TOOLCHAIN_ROOT")
                                 or (HERE.parent if (HERE.parent / "sv0c").is_dir()
                                     else HERE.parent / "sv0-toolchain")))
    ap.add_argument("--emit-only", type=Path, help="write the generated sv0 program here and exit")
    ap.add_argument("--c-only", action="store_true")
    ap.add_argument("--vm-only", action="store_true")
    ap.add_argument("--strict-vm", action="store_true",
                    help="fail (exit 1) on a VM-backend miss too; by default the "
                         "VM leg is advisory (see the SML-110.99.9 note below)")
    args = ap.parse_args()

    with (FIXTURES / "rounding.csv").open() as f:
        rounding_rows = list(csv.DictReader(f))
    with (FIXTURES / "trig.csv").open() as f:
        trig_rows = list(csv.DictReader(f))

    src, checks, skipped = generate(rounding_rows, trig_rows)
    print(f"run_fixture_parity: {len(checks)} checks generated "
          f"({len(rounding_rows)} rounding rows x{len(ROUNDING_FUNCS)} + "
          f"{len(trig_rows) - len(skipped)} trig rows), {len(skipped)} PANIC row(s) skipped")
    for s in skipped:
        print(f"  skip  {s}")

    if args.emit_only:
        args.emit_only.write_text(src, encoding="utf-8")
        print(f"run_fixture_parity: wrote {args.emit_only}")
        return 0

    tc = args.toolchain_root
    with tempfile.TemporaryDirectory(prefix="sv0mathlib_fixparity_") as tmp:
        project = stage_project(src, Path(tmp))
        c_exit = c_out = v_exit = None
        if not args.vm_only:
            c_exit, c_out = run_c(project, tc)
        if not args.c_only:
            v_exit, v_out = run_vm(project, tc)

    ok = True         # C-backend result — always gates
    vm_ok = True      # VM-backend result — gates only under --strict-vm
    if c_exit is not None:
        if c_exit == 0:
            print("run_fixture_parity: C backend   — all fixture rows match (exit 0)")
        else:
            ok = False
            print(f"run_fixture_parity: C backend   — FAIL: {decode(c_exit, checks)}", file=sys.stderr)
            if isinstance(c_exit, str):
                print(f"  {c_out}", file=sys.stderr)
    if v_exit is not None:
        if v_exit == 0:
            print("run_fixture_parity: VM backend  — all fixture rows match (exit 0)")
        else:
            vm_ok = False
            tag = "FAIL" if args.strict_vm else "WARN (advisory)"
            if v_exit == "CONTRACT_VIOLATION":
                detail = f"a requires/ensures aborted the run — {v_out}"
            else:
                detail = decode(v_exit, checks)
            print(f"run_fixture_parity: VM backend  — {tag}: {detail}", file=sys.stderr)
            print("  The VM leg is advisory by default: it passes on SML/NJ 2026.1 but a "
                  "transcendental\n  ensures aborts under the SML/NJ 110.99.9 the CI runner "
                  "uses (BUGS.md). The exit-code\n  cross-backend gate (vm_behavioral_parity) "
                  "and the C-backend row check above are unaffected.", file=sys.stderr)
    if (c_exit is not None and v_exit is not None
            and isinstance(c_exit, int) and isinstance(v_exit, int) and c_exit != v_exit):
        gate = args.strict_vm
        if gate:
            ok = False
        print(f"run_fixture_parity: cross-backend exit mismatch — "
              f"C={c_exit!r}, VM={v_exit!r}"
              f"{'' if gate else ' (advisory)'}", file=sys.stderr)

    if args.strict_vm and not vm_ok:
        ok = False

    passed = ok and (vm_ok or not args.strict_vm)
    if passed and not vm_ok:
        print("run_fixture_parity: PASS (C backend gated; VM leg advisory — see WARN above)")
    else:
        print("run_fixture_parity: PASS" if passed else "run_fixture_parity: FAIL")
    return 0 if passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
